/**
 * 千手-淘淘英语学习 · 例句库（语境/句子题内容）
 * 由人工编写的基础例句，按单词原形（小写）索引。
 * 用途：① 语境理解题（句中选义/填空）② 离线模式下的例句展示。
 * 说明：仅覆盖词库中的常见教学词；未收录的词不出语境题，不强行生成。
 */
var EXAMPLE_BANK = {
  "edge": { sentence: "He stood at the edge of the lake, looking at the water.", translation: "他站在湖边，望着水面。" },
  "valley": { sentence: "The river runs through a wide green valley.", translation: "这条河穿过一条宽阔的绿色山谷。" },
  "glacier": { sentence: "The glacier moves slowly down the mountain.", translation: "冰川缓缓向山下移动。" },
  "vast": { sentence: "The desert is vast and almost empty of people.", translation: "这片沙漠辽阔而几乎无人。" },
  "melt": { sentence: "The snow begins to melt when spring comes.", translation: "春天到来时雪开始融化。" },
  "ban": { sentence: "The school decided to ban phones in class.", translation: "学校决定禁止在课堂上使用手机。" },
  "boundary": { sentence: "The river forms the boundary between the two villages.", translation: "这条河是两个村庄的分界线。" },
  "adopt": { sentence: "The committee adopted the new plan yesterday.", translation: "委员会昨天采纳了新计划。" },
  "accompany": { sentence: "His father accompanied him to the station.", translation: "他父亲陪他去了车站。" },
  "sour": { sentence: "These grapes taste sour; I don't like them.", translation: "这些葡萄尝起来很酸，我不喜欢。" },
  "journalist": { sentence: "The journalist is writing a story about the local market.", translation: "这位记者正在写一篇关于本地市场的报道。" },
  "label": { sentence: "Please read the label before you take the medicine.", translation: "服药前请先阅读标签说明。" },
  "cream": { sentence: "She put some cream in her coffee.", translation: "她在咖啡里加了些奶油。" },
  "stretch": { sentence: "The road stretches for miles across the plain.", translation: "这条路在平原上延伸数英里。" },
  "cycle": { sentence: "I cycle to school every morning.", translation: "我每天早晨骑自行车上学。" },
  "route": { sentence: "Which route do you usually take to work?", translation: "你上班通常走哪条路线？" },
  "ahead": { sentence: "The finish line is still ahead of us.", translation: "终点线还在我们前方。" },
  "theme": { sentence: "The theme of this meeting is environmental protection.", translation: "这次会议的主题是环境保护。" },
  "appeal": { sentence: "This game appeals to young students.", translation: "这个游戏对年轻学生很有吸引力。" },
  "wander": { sentence: "We wandered around the old town for an hour.", translation: "我们在老城里逛了一个小时。" },
  "amusement": { sentence: "The amusement park is crowded on weekends.", translation: "周末游乐园里人很多。" },
  "enormous": { sentence: "The building is enormous and can hold thousands of people.", translation: "这座建筑非常大，可容纳数千人。" },
  "swing": { sentence: "The monkey swung from one tree to another.", translation: "猴子从一棵树荡到另一棵树上。" },
  "fashion": { sentence: "Bright colors are in fashion this summer.", translation: "今年夏天流行亮色。" },
  "rare": { sentence: "It is rare to see snow in this city.", translation: "这座城市很少见到雪。" },
  "steam": { sentence: "Steam rose from the hot soup.", translation: "热汤冒出蒸汽。" },
  "superb": { sentence: "The view from the hill is superb.", translation: "从山丘上看到的景色极佳。" },
  "display": { sentence: "The shop displays its new products in the window.", translation: "商店在橱窗里展示新产品。" },
  "appetite": { sentence: "A long walk gives me a good appetite.", translation: "走长一段路让我胃口大开。" },
  "entertainment": { sentence: "The movie is good entertainment for a rainy day.", translation: "这部电影是下雨天很好的娱乐。" },
  "interaction": { sentence: "Good interaction between students and teachers helps learning.", translation: "师生之间良好的互动有助于学习。" },
  "vary": { sentence: "Prices vary from shop to shop.", translation: "价格因商店而异。" },
  "appropriate": { sentence: "Please wear appropriate clothes for the interview.", translation: "请穿适合面试的衣服。" },
  "approve": { sentence: "Her parents approved of her decision to study abroad.", translation: "她的父母赞同她出国学习的决定。" },
  "gesture": { sentence: "He made a gesture to show he was sorry.", translation: "他做了一个手势表示抱歉。" },
  "witness": { sentence: "I witnessed the whole accident on the street.", translation: "我在街上目睹了整起事故。" },
  "employ": { sentence: "The company employs fifty workers.", translation: "这家公司雇用了五十名工人。" },
  "identical": { sentence: "The two jackets look identical in color and size.", translation: "这两件夹克在颜色和尺码上看起来一模一样。" },
  "interpret": { sentence: "Please interpret the sentence into Chinese.", translation: "请把这个句子翻译成中文。" },
  "differ": { sentence: "The two opinions differ greatly.", translation: "这两种观点差别很大。" },
  "barrier": { sentence: "Language is not always a barrier to friendship.", translation: "语言并不总是友谊的障碍。" },
  "reliable": { sentence: "He is a reliable friend whom I can trust.", translation: "他是我可以信赖的可靠朋友。" },
  "incident": { sentence: "The incident happened near the school gate.", translation: "事件发生在校门口附近。" },
  "trial": { sentence: "The new method is still on trial.", translation: "新方法仍在试验中。" },
  "slight": { sentence: "There is a slight difference between the two words.", translation: "这两个词之间略有差别。" },
  "assess": { sentence: "Teachers assess students' progress every month.", translation: "老师每月评估学生的进步。" },
  "internal": { sentence: "The internal structure of the machine is complex.", translation: "机器的内部结构很复杂。" },
  "reveal": { sentence: "The study revealed an important fact.", translation: "这项研究揭示了一个重要事实。" },
  "clarify": { sentence: "Can you clarify the meaning of this sentence?", translation: "你能解释一下这个句子的意思吗？" },
  "tendency": { sentence: "He has a tendency to arrive late.", translation: "他有迟到的倾向。" },
  "imply": { sentence: "His silence implied that he agreed.", translation: "他的沉默暗示他同意了。" },
  "barely": { sentence: "I barely had time to finish the work.", translation: "我几乎没有时间完成工作。" },
  "occupy": { sentence: "The books occupy most of the shelf.", translation: "书占满了书架的大部分。" },
  "distract": { sentence: "The noise distracted me from my homework.", translation: "噪音使我无法专心做作业。" },
  "perceive": { sentence: "We perceive the problem in different ways.", translation: "我们对这个问题有不同看法。" },
  "distinguish": { sentence: "Can you distinguish the twins apart?", translation: "你能分辨出这对双胞胎吗？" },
  "anxiety": { sentence: "She felt anxiety before the exam.", translation: "考试前她感到焦虑。" },
  "adjust": { sentence: "It took him a while to adjust to the new school.", translation: "他过了一段时间才适应新学校。" },
  "react": { sentence: "How did she react to the good news?", translation: "她对这个好消息反应如何？" },
  "component": { sentence: "Each component of the machine is important.", translation: "机器的每个部件都很重要。" },
  "tone": { sentence: "He spoke in a quiet tone.", translation: "他说话语气很轻。" },
  "devote": { sentence: "She devotes most of her time to reading.", translation: "她把大部分时间用来读书。" },
  "shortage": { sentence: "The city faces a shortage of clean water.", translation: "这座城市面临清洁水源短缺。" },
  "tackle": { sentence: "We must tackle the problem as soon as possible.", translation: "我们必须尽快解决这个问题。" },
  "crisis": { sentence: "The country is going through an economic crisis.", translation: "这个国家正经历经济危机。" },
  "boost": { sentence: "Winning the game boosted our confidence.", translation: "赢得比赛增强了我们的信心。" },
  "yield": { sentence: "The new seeds yield more rice than before.", translation: "新种子比以前产出更多大米。" },
  "convince": { sentence: "I convinced him to join the team.", translation: "我说服他加入了团队。" },
  "attain": { sentence: "She attained her goal after years of hard work.", translation: "经过多年努力，她实现了目标。" },
  "conventional": { sentence: "Farmers still use conventional methods on the farm.", translation: "农民们仍然在农场使用传统方法。" },
  "intense": { sentence: "The training is intense but rewarding.", translation: "训练强度很大但很有收获。" },
  "expand": { sentence: "The company plans to expand its business.", translation: "公司计划扩大业务。" },
  "output": { sentence: "The factory increased its output this year.", translation: "工厂今年提高了产量。" },
  "estimate": { sentence: "It is difficult to estimate the cost exactly.", translation: "很难准确估算成本。" },
  "domestic": { sentence: "Domestic products are popular in our store.", translation: "国产品在我们的商店里很受欢迎。" },
  "consumption": { sentence: "Too much sugar is bad for health and increases consumption.", translation: "摄入过多糖对健康有害。" },
  "generate": { sentence: "The machine generates electricity from wind.", translation: "这台机器用风发电。" },
  "leisure": { sentence: "He reads books in his leisure time.", translation: "他在空闲时间读书。" },
  "grain": { sentence: "Farmers store grain in the warehouse.", translation: "农民把谷物储存在仓库里。" },
  "vision": { sentence: "The company has a clear vision for the future.", translation: "公司对未来有清晰的愿景。" },
  "urban": { sentence: "Urban life is busy but convenient.", translation: "城市生活忙碌但方便。" },
  "extension": { sentence: "They built an extension to the house.", translation: "他们给房子加盖了扩建部分。" },
  "chemical": { sentence: "The farm uses fewer chemical fertilizers now.", translation: "农场现在使用较少的化肥。" },
  "wheat": { sentence: "Wheat grows well in the north of China.", translation: "小麦在中国北方长势良好。" },
  "flavour": { sentence: "The soup has a rich flavour.", translation: "这汤味道浓郁。" },
  "nutrition": { sentence: "Good nutrition is important for students.", translation: "良好的营养对学生很重要。" },
  "organic": { sentence: "Organic vegetables are more expensive but healthier.", translation: "有机蔬菜更贵但更健康。" },
  "widespread": { sentence: "The custom is widespread in this area.", translation: "这种习俗在该地区很普遍。" },
  "digest": { sentence: "It takes time to digest hard food and new ideas.", translation: "消化难消化的食物和新观点都需要时间。" },
  "essential": { sentence: "Water is essential to all living things.", translation: "水对一切生物都是必不可少的。" },
  "mineral": { sentence: "Milk is rich in minerals.", translation: "牛奶富含矿物质。" },
  "alternative": { sentence: "We need an alternative plan in case it rains.", translation: "我们需要一个备用方案以防下雨。" },
  "instance": { sentence: "For instance, you can take the bus instead.", translation: "例如，你可以改乘公交车。" },
  "batch": { sentence: "The workers make a new batch of cakes every day.", translation: "工人们每天做一批新蛋糕。" },
  "depth": { sentence: "The depth of the lake is about ten meters.", translation: "湖的深度约十米。" },
  "root": { sentence: "The roots of the tree are deep in the soil.", translation: "树的根深深扎在泥土里。" },
  "entirely": { sentence: "The problem is entirely different from what I expected.", translation: "这个问题与我预想的完全不同。" },
  "aspect": { sentence: "We should consider every aspect of the plan.", translation: "我们应该考虑计划的每个方面。" }
};